version: "1.0"
info:
  model: int-scaffold
packages:
- name: TestNewP12Project
  gitServerName: p1
  gitUrl: https://github.com/PoojaAnandGit
  gitUsername: PoojaAnandGit
  gitBranch: main
services:
- serviceName: project.testnewp12.integrations:newEdgeflow
  packages:
  - name: TestNewP12Project
    version: "1.0"
